CREATE OR REPLACE PROCEDURE DELETE_FROM_TABLES
  (CODE OUT NUMBER)
  IS
  BEGIN
    DELETE FROM REZERWACJE;
    DELETE FROM ZAKUPY;
    DELETE FROM BILETY;
    DELETE FROM KARNETY;
    DELETE FROM TYPY_KARNETOW;
    DELETE FROM PROMOCJE;
    DELETE FROM KLIENCI;
    DELETE FROM TYPY_KLIENTOW;
    DELETE FROM CENY;
    DELETE FROM IMPREZY;
    DELETE FROM TYPY_IMPREZ;
    DELETE FROM MIEJSCA;
    DELETE FROM SEKTORY;
    DELETE FROM STADIONY;
    DELETE FROM TYPY_SEKTOROW;
    COMMIT;
    CODE:=0;
  END;
/


