CREATE OR REPLACE PROCEDURE POPULATE
  (CODE OUT NUMBER)
  IS
  BEGIN
    WSTAW_DO_TYPY_SEKTOROW();
    WSTAW_DO_TYPY_IMPREZ();
    WSTAW_DO_TYPY_KLIENTOW();
    WSTAW_DO_PROMOCJE();
    WSTAW_DO_TYPY_KARNETOW();

    STWORZ_STADIONY(1);
    STWORZ_IMPREZY(5,20);
    STWORZ_KLIENTOW(10);
    STWORZ_KARNETY(10);
    STWORZ_REZERWACJE(5);
    STWORZ_ZAKUPY(100);
    COMMIT;
    CODE:=0;
  END;
/
